# Generated by Django 4.1.4 on 2022-12-10 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Category for publication",
                "verbose_name_plural": "Category for publication",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="app_blog.category",
                verbose_name="Category",
            ),
        ),
    ]
