# Generated by Django 4.1.4 on 2022-12-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_blog", "0002_alter_category_options_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleimage",
            options={
                "verbose_name": "Категорія для публікації",
                "verbose_name_plural": "Категорії для публікації",
            },
        ),
    ]
